services:
  scheduler:
    image: chesspro13/llamapi
    ports:
      - "27415:27415"
    environment:
      AI_NODE: <Node IP>
      ORIGIN_URL: <ORIGIN URL>
      AI_NODES: <Nodes IP>
      AI_MODEL: <AI Model>
      CUSTOM_PROMPT: <true | false>
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: <REDIS PASSWORD>
    depends_on:
      - cache
  cache:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning